spring.application.name=NOTIFICATION-SERVICE

server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/notification_db
spring.datasource.username=root
spring.datasource.password=Madhavi@26226

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

