#####################################################
# APPLICATION
#####################################################

spring.application.name=discovery-server
server.port=8761

#####################################################
# EUREKA SERVER CONFIGURATION
#####################################################

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost

#####################################################
# EUREKA SERVER SETTINGS
#####################################################

eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=60000

#####################################################
# ACTUATOR
#####################################################

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

#####################################################
# LOGGING
#####################################################

logging.level.com.netflix.eureka=INFO
logging.level.com.completebank.discovery=INFO
logging.level.org.springframework=INFO